using System;
using System.Collections.Generic;
using System.Text;

namespace DQAsset
{
    public enum UE4Versions : int
    {
        VER_UE4_OLDEST_LOADABLE_PACKAGE = 214,
        VER_UE4_WORLD_LEVEL_INFO = 224,
        VER_UE4_ADDED_CHUNKID_TO_ASSETDATA_AND_UPACKAGE = 278,
        VER_UE4_CHANGED_CHUNKID_TO_BE_AN_ARRAY_OF_CHUNKIDS = 326,
        VER_UE4_ENGINE_VERSION_OBJECT = 336,
        VER_UE4_LOAD_FOR_EDITOR_GAME = 365,
        VER_UE4_ADD_STRING_ASSET_REFERENCES_MAP = 384,
        VER_UE4_PACKAGE_SUMMARY_HAS_COMPATIBLE_ENGINE_VERSION = 444,
        VER_UE4_SERIALIZE_TEXT_IN_PACKAGES = 459,
        VER_UE4_COOKED_ASSETS_IN_EDITOR_SUPPORT = 485,
        VER_UE4_NAME_HASHES_SERIALIZED = 504,
        VER_UE4_PRELOAD_DEPENDENCIES_IN_COOKED_EXPORTS = 507,
        VER_UE4_TemplateIndex_IN_COOKED_EXPORTS = 508,
        VER_UE4_ADDED_SEARCHABLE_NAMES = 510,
        VER_UE4_64BIT_EXPORTMAP_SERIALSIZES = 511,
        VER_UE4_ADDED_PACKAGE_SUMMARY_LOCALIZATION_ID = 516,
        VER_UE4_ADDED_PACKAGE_OWNER = 518,
    }
}
